heat_template_version: 2014-10-16

description: |
  Deploy Nginx server with Ansible

parameters:
  image_id:
    type: string
    default: 9ab886e6-c75c-4279-9418-dd1ba7876335
  network_id:
    type: string
    default: 0c9b2542-3d24-48b6-8de8-8c4f8a187ccc
  server_name:
    type: string
    default: centos_w_nginx
  key_name:
    type: string
    default: mykey

resources:
  nginx_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Install and run Nginx
          connection: local
          hosts: localhost
          tasks:
           - name: Install Nginx
             yum: name=nginx state=installed 
             notify:
              - Start Nginx
          handlers:
           - name: Start Nginx
             service: name=nginx state=started
  
  deploy_nginx:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config: 
        get_resource: nginx_config
      server: { get_resource: server }
  
  floatingip:
    type: OS::Nova::FloatingIP
    properties:
      pool: nova

  floatingipassoc:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingip }
      server_id: { get_resource: server }

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: m1.small
      networks:
        - network: { get_param: network_id }
      key_name: { get_param: key_name }
      software_config_transport: POLL_TEMP_URL
      user_data_format: SOFTWARE_CONFIG
      name: { get_param: server_name }

